apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::350883800889:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-UpmLgTxoOJ1v
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::350883800889:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-UpmLgTxoOJ1v\n  username: system:node:{{EC2PrivateDNSName}}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-12-05T09:59:00Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1335","uid":"b5259f62-daaf-4836-8ecf-de6c29ba541a"}}
  creationTimestamp: "2023-12-05T09:59:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "20988"
  uid: b5259f62-daaf-4836-8ecf-de6c29ba541a
